### ISSUE TITLE
`ll.xist.xsc.Element` is not hashable

### ISSUE THREAD

**Issue by vectro** [LivingLogic/LivingLogic.Python.xist#1]
Is this intentional? `CharacterData` is hashable even though it is (also) mutable.

Ideally all descendents of `Node` would be hashable.

**Comment by doerwalter** [comment]
The fact that `Element` is not hashable is intentional.

---

For an object to be usable as a dictionary key:

1. `__eq__` and `__hash__` must be consistent, i.e. for two objects `a` and `b` when `a == b` holds, `hash(a) == hash(b)` must also hold. ([The `object.__hash__` documentation](https://docs.python.org/3/reference/datamodel.html?highlight=__hash__#object.__hash__) states "The only required property is that objects which compare equal have the same hash value").

2. Furthermore the hash value must be stable (otherwise you could put an object into a dict, do something to the object that changes its hash value, and then the dict wouldn't be able to find that object again, although it has been put into the dict).

The default implementation of `__eq__` does an identity comparison, i.e. two objects are only equal if they are the same object. In that situation `__hash__` is simple, since the identity is just the memory address and that won't change.

But I wanted to have an `__eq__` implementation that does a value comparison, so that two nodes are equal when they have the same structure, e.g.:

```python
>>> html.ul(html.li(1), html.li(2)) == html.ul(html.li(1), html.li(2))
True
```

And I also wanted XIST nodes to be mutable, so you can build XIST trees step by step, i.e.:

```python
e = html.ul()
e.append(html.li(1))
e.append(html.li(2))
```

For that reason XIST nodes can't be hashable.

---

So why is `CharacterData` hashable? Well, there's not much structure to `xsc.CharacterData`. It's basically just a fancy string. It's rather unlikely that a `CharacterData` objects gets created step by step. But it might be useful to be able to use `CharacterData` objects as dictionary keys. So this basically boils down to "Don't change `CharacterData` objects if you use them as dictionary keys". I don't know if it would be feasable to subclass `CharacterData` from `str` to make `CharacterData` really immutable (well, except for the `startloc` attribute, which would still be mutable, but is ignored for `__hash__`, so that shouldn't be a problem).

**Comment by vectro** [comment]
Hmm, well that makes sense. I think this is okay to close.

I suppose I would just like to register my opinion that immutable values are much easier to reason about and this library would be even better if one could arrange for all `Node`s to be immutable.
